# ghostty terminal emulator colors
# genrated by rizzoo

# --- Special ---
foreground   = {{ on_surface }}
background   = {{ background }}
cursor-color = {{ primary }}

# --- Normal colors ---
palette =  0={{ background }}
palette =  1={{ error }}
palette =  2={{ primary }}
palette =  3={{ secondary }}
palette =  4={{ tertiary }}
palette =  5={{ on_secondary_container }}
palette =  6={{ on_primary_container }}
palette =  7={{ on_surface }}

# --- Bright colors ---
palette =  8={{ surface_bright }}
palette =  9={{ error }}
palette = 10={{ primary }}
palette = 11={{ secondary }}
palette = 12={{ tertiary }}
palette = 13={{ on_secondary_container }}
palette = 14={{ on_primary_container }}
palette = 15={{ on_surface }}
