foreground         {{ on_surface }}
background         {{ background }}
cursor             {{ primary }}

active_tab_foreground     {{ on_primary }}
active_tab_background     {{ primary }}
inactive_tab_foreground   {{ outline }}
inactive_tab_background   {{ surface_container }}

active_border_color   {{ primary }}
inactive_border_color {{ surface_container }}
bell_border_color     {{ error }}

color0  {{ surface }}
color1  {{ error }}
color2  {{ on_tertiary_container }}
color3  {{ tertiary }}
color4  {{ on_primary_container }}
color5  {{ secondary }}
color6  {{ outline }}
color7  {{ on_surface }}
color8  {{ outline_variant }}
color9  {{ error_container }}
color10 {{ tertiary_fixed_dim }}
color11 {{ tertiary_fixed }}
color12 {{ primary }}
color13 {{ secondary_fixed_dim }}
color14 {{ on_surface_variant }}
color15 {{ inverse_surface }}
