# colors_tty.sh — generated by rwal
# Source this file or run it to apply colors to the Linux TTY.
# Only has effect on a real TTY (not a terminal emulator).

if [ "$TERM" = "linux" ]; then
    printf '\e]P0{{ background }}'             # 0: black
    printf '\e]P1{{ error }}'              # 1: red
    printf '\e]P2{{ primary }}'            # 2: green
    printf '\e]P3{{ secondary }}'          # 3: yellow
    printf '\e]P4{{ tertiary }}'           # 4: blue
    printf '\e]P5{{ on_secondary_container }}' # 5: magenta
    printf '\e]P6{{ on_primary_container }}'   # 6: cyan
    printf '\e]P7{{ on_surface }}'         # 7: white
    printf '\e]P8{{ surface_bright }}'     # 8: bright black
    printf '\e]P9{{ error }}'              # 9: bright red
    printf '\e]PA{{ primary }}'            # A: bright green
    printf '\e]PB{{ secondary }}'          # B: bright yellow
    printf '\e]PC{{ tertiary }}'           # C: bright blue
    printf '\e]PD{{ on_secondary_container }}' # D: bright magenta
    printf '\e]PE{{ on_primary_container }}'   # E: bright cyan
    printf '\e]PF{{ on_surface }}'         # F: bright white
    clear                                      # flush color artifacts
fi
