-- nvim colors
-- generated by rizzoo

return {
  bg         = "{{ surface }}",
  fg         = "{{ on_surface }}",
  surface    = "{{ surface_container }}",
  surface_hi = "{{ surface_container_high }}",
  primary    = "{{ primary }}",
  secondary  = "{{ secondary }}",
  tertiary   = "{{ tertiary }}",
  error      = "{{ error }}",
  outline    = "{{ outline }}",
  dim        = "{{ outline_variant }}",
}
