# tty colors
# generated by rizoo
# note: source this file or run it to apply colors to the Linux TTY.
# only has effect on a real TTY (not a terminal emulator, probably).

if [ "$TERM" = "linux" ]; then
    printf '\e]P0{{ background }}'
    printf '\e]P1{{ error }}'
    printf '\e]P2{{ primary }}'
    printf '\e]P3{{ secondary }}'
    printf '\e]P4{{ tertiary }}'
    printf '\e]P5{{ on_secondary_container }}'
    printf '\e]P6{{ on_primary_container }}'
    printf '\e]P7{{ on_surface }}'
    printf '\e]P8{{ surface_bright }}'
    printf '\e]P9{{ error }}'
    printf '\e]PA{{ primary }}'
    printf '\e]PB{{ secondary }}'
    printf '\e]PC{{ tertiary }}'
    printf '\e]PD{{ on_secondary_container }}'
    printf '\e]PE{{ on_primary_container }}'
    printf '\e]PF{{ on_surface }}'
    clear
fi
