# ╭──────────────────────────────╮
# │             Blur             │
# ╰──────────────────────────────╯
blur:
{
  method = "gaussian";
#  strength = 0;
#  background = false;
#  background-frame = false;
};
