
#               ░██
#
#    ░████████  ░██ ░███████   ░███████  ░█████████████
#    ░██    ░██ ░██░██    ░██ ░██    ░██ ░██   ░██   ░██
#    ░██    ░██ ░██░██        ░██    ░██ ░██   ░██   ░██
#    ░███   ░██ ░██░██    ░██ ░██    ░██ ░██   ░██   ░██
#    ░██░█████  ░██ ░███████   ░███████  ░██   ░██   ░██
#    ░██
#    ░██
#
#	 github: @plgbrlism
#	 tiktok: @fuzzbuzz.tech

@include "conf/shadows.conf"
@include "conf/fading.conf"
@include "conf/opacity.conf"
@include "conf/corners.conf"
@include "conf/blur.conf"
@include "conf/general.conf"
@include "conf/rules.conf"
