
#               ░██
#
#    ░████████  ░██ ░███████   ░███████  ░█████████████
#    ░██    ░██ ░██░██    ░██ ░██    ░██ ░██   ░██   ░██
#    ░██    ░██ ░██░██        ░██    ░██ ░██   ░██   ░██
#    ░███   ░██ ░██░██    ░██ ░██    ░██ ░██   ░██   ░██
#    ░██░█████  ░██ ░███████   ░███████  ░██   ░██   ░██
#    ░██
#    ░██
#
#	 github: @plgbrlism
#	 tiktok: @fuzzbuzz.tech

@include "shadows.conf"
@include "fading.conf"
@include "opacity.conf"
@include "corners.conf"
@include "blur.conf"
@include "general.conf"
@include "rules.conf"
