# ~~ hyprlock ~~

source = ~/.config/hypr/colors/colors.conf 
source = ~/.config/hypr/wallpaper/wallpaper.conf
source = ~/.config/hypr/fonts/fonts.conf
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/time-date.conf
source = ~/.config/hypr/conf/password.conf
source = ~/.config/hypr/conf/user.conf
source = ~/.config/hypr/conf/battery.conf
