-- nvim colors
-- generated by rizzoo

return {
  bg         = "#121317",
  fg         = "#e2e2e7",
  surface    = "#1e2023",
  surface_hi = "#282a2e",
  primary    = "#8fa4c7",
  secondary  = "#9ba3b4",
  tertiary   = "#b29bb8",
  error      = "#ff7b6e",
  outline    = "#8e9098",
  dim        = "#44474d",
}
