-- nvim colors
-- generated by rizzoo

return {
  bg         = "#191212",
  fg         = "#eedfe0",
  surface    = "#251e1e",
  surface_hi = "#302829",
  primary    = "#cf939b",
  secondary  = "#bc9b9e",
  tertiary   = "#bf9d78",
  error      = "#ff7b6e",
  outline    = "#9d8d8e",
  dim        = "#514445",
}
