-- nvim colors
-- generated by rizzoo

return {
  bg         = "#141317",
  fg         = "#e6e1e7",
  surface    = "#201f23",
  surface_hi = "#2b292e",
  primary    = "#a79dc8",
  secondary  = "#a6a0b4",
  tertiary   = "#c297a6",
  error      = "#ff7b6e",
  outline    = "#938f98",
  dim        = "#48454d",
}
