#    
#        ░████                          ░██    
#       ░██                             ░██    
#    ░████████  ░███████   ░███████  ░████████ 
#       ░██    ░██    ░██ ░██    ░██    ░██    
#       ░██    ░██    ░██ ░██    ░██    ░██    
#       ░██    ░██    ░██ ░██    ░██    ░██    
#       ░██     ░███████   ░███████      ░████ 
#                                              
#	 github: @plgbrlism
#	 tiktok: @fuzzbuzz.tech

[main]
include= ~/.config/foot/color-foot.ini 
