# do not use this polybar custom script, the polling rate interval is not desirable
# the native backlight module is more better
# although you can use it if you can tolerate the delayed update in bar by increasing interval(seconds)

[module/brightness]
type = custom/script
exec = ~/.config/polybar/scripts/brightness-display.sh
interval = 1
label = 󰃠  %output%
label-foreground = ${colors.foreground}
scroll-up = ~/.config/polybar/scripts/brightness-control.sh --up
scroll-down = ~/.config/polybar/scripts/brightness-control.sh --down
