# Dracula

# Client colors
# Format: client.<state> <border> <background> <text> <indicator> <child_border>

client.focused          #f8f8f2 #bd93f9 #f8f8f2 #bd93f9 #f8f8f2
client.focused_inactive #bd93f9 #282a36 #f8f8f2 #44475a #bd93f9
client.unfocused        #bd93f9 #282a36 #f8f8f2 #282a36 #bd93f9
client.urgent           #ff5555 #ff5555 #f8f8f2 #ff5555 #ff5555
client.placeholder      #282a36 #282a36 #282a36 #282a36 #282a36

client.background       #282a36
