# ~~~ Background ~~~

background {
    path = ~/Pictures/funmehmehs/dank-shrek.jpg
    blur_passes = 1
}

# ~~~ General Settings ~~~

general {
    ignore_empty_input = true
    hide_cursor = true
}

# ~~~ Animations ~~~

animations {
    animation = fade,    1, 6, default
    animation = fadeIn,  1, 6, default
    animation = fadeOut, 1, 6, default
}

# ~~~ Clock & Date ~~~

# Time
label {
    text = $TIME
    color = rgba(216, 222, 233, 0.70)
    font_size = 30
    font_family = JetBrains Mono Nerd Font Propo
    position = 20, 55
    halign = left
    valign = bottom
}

    
# Date
label {
    text = cmd[update:1000] echo -e "$(date +"%A, %d %B")"
    color = rgba(216, 222, 233, 0.70)
    font_size = 25
    font_family = JetBrains Mono Nerd Font Propo
    position = 20, 20
    halign = left
    valign = bottom
}

# ~~~ Login Pane ~~~

# Window
shape {
    color = rgba(100, 114, 125, 0.4)
    size = 350, 120
    rounding = 13
    position = -20, 20
    halign = right
    valign = bottom
    zindex = 0
    }
    
# Profile Pic
image {
    path = ~/Pictures/icons/f2c8c3a951e382b4b4b22b56b582d054.jpg
    border_size = 0
    size = 100
    rounding = 13           # -1 = circle
    rotate = 10
    reload_time = -1
    reload_cmd = 
    position = -260, 30
    halign = right
    valign = bottom
    }
    
# Drop Shadow for the Profile Picture
shape {
    color = rgba(1, 1, 1, 0.6)
    size = 100, 100
    rounding = 13
    rotate = 10
    position = -264, 21
    halign = right
    valign = bottom
    zindex = 0
    }
    
# Username
label {
    text = $USER
    color = rgba(216, 222, 233, 0.8)
    font_size = 20
    font_family = JetBrains Mono Nerd Font Propo
    position = -150, 85
    halign = right
    valign = bottom
}

# ~~~ Password Input Field ~~~

input-field {
    size = 210, 40
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.8
    dots_center = true
    outer_color = rgba(1, 1, 1, 0)
    inner_color = rgba(100, 114, 125, 0.5)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = JetBrains Mono Nerd Font Propo
    placeholder_text = <span foreground="##ffffff99">Password</span>
    hide_input = false
    position = -37, 37
    halign = right
    valign = bottom
}
