# ~/.config/rizzoo/config.toml
# See `rizzoo --help` for all available flags and values.
#
# Uncomment and edit only what you want to override.

#style = "tonal-spot"
#mode = dark
#contrast = "standard"
pick = 0
#prefer = "darkness"
 
#[wallpaper]
#set = false
#command = "awww img {{ image }} --transition-type random"

[custom_colors]
success    = { color = "#386B35", blend = true }

[btop]
template = "btop.theme"
output   = "~/.config/btop/themes/dynamic.theme"

[antigravity]
template = "antigravity.json"
output   = "~/.config/Antigravity/User/settings.json"

[alacritty]
template = "colors-alacritty.toml"
output   = "~/.config/alacritty/colors/variants/dynamic.toml"
#enabled  = false

[ghostty]
template = "colors-ghostty.conf"
output   = "~/.config/ghostty/colors/variants/dynamic.ghostty" 

[i3]
template = "colors-i3"
output   = "~/.config/i3/colors/variants/dynamic.conf" 

[kitty]
template = "colors-kitty.conf"
output   = "~/.config/kitty/colors/variants/dynamic.conf" 

[micro]
template = "colors-micro.micro"
output   = "~/.config/micro/colorschemes/dynamic.micro"

[polybar]
template = "colors-polybar.ini"
output   = "~/.config/polybar/colors/variants/dynamic.ini"
post_hook = "polybar-msg cmd restart" 

[rofi]
template = "colors-rofi.rasi"
output   = "~/.config/rofi/colors/variants/dynamic.rasi"

[sway]
template = "colors-sway"
output   = "~/.config/sway/colors/variants/dynamic.conf" 

[waybar]
template = "colors-waybar.css"
output   = "~/.config/waybar/colors/variants/dynamic.css"
post_hook = "killall -SIGUSR2 waybar"

[Xresources]
template = "colors.Xresources"
output   = "~/.Xresources"

[dunst]
template = "colors-dunstrc"
output   = "~/.config/dunst/dunstrc"
post_hook = "dunstctl reload"

[peaclock]
template = "colors-peaclock.conf"
output   = "~/.peaclock/config"

[foot]
template = "colors-foot.ini"
output   = "~/.config/foot/color-foot.ini"

[cava]
template = "colors-cava.ini"
output   = "~/.config/cava/config"

[hyprlock]
template = "colors-hyprlock.conf"
output   = "~/.config/hypr/colors/variants/dynamic.conf"

[hyprlock-bg]
template = "hyprlock-bg-wallpaper.conf"
output   = "~/.config/hypr/wallpaper/variants/dynamic.conf"

[pywalfox]
template = "colors-firefox.json"
output   = "~/.cache/wal/colors.json"
post_hook = "pywalfox update"

[noctalia]
template = "colors-noctalia.json"
output   = "~/.config/noctalia/palettes/rizzoo.json"

# GTK3 / GTK4(libadwaita) Themes
# note: only one gtk theme must have an active post_hook

#[colloid]
#template = "colloid-colors.scss"
#output   = "~/dotfiles-pub/gtk/colloid/Colloid-gtk-theme/src/sass/_colors.scss"
#post_hook = "~/dotfiles-pub/gtk/colloid/reload.sh"


#[graphite]
#template = "graphite-colors.scss"
#output   = "~/dotfiles-pub/gtk/graphite/Graphite-gtk-theme/src/sass/_colors.scss"
#post_hook = "~/dotfiles-pub/gtk/graphite/reload.sh"

[mac-colors]
template = "mac-colors.scss"
output   = "~/dotfiles-pub/gtk/mac-tahoe/MacTahoe-gtk-theme/src/sass/_colors.scss"
post_hook = "~/dotfiles-pub/gtk/mac-tahoe/reload.sh"


# Test Templates
[material-css]
template = "material-theme.css"
output = "~/projects/tmp/rizzoo-material-theme.css"

[material-kotlin]
template = "MaterialColors.kt"
output = "~/projects/tmp/MaterialColors.kt"
