# ~~ native terminal font/zoom control ~~
map ctrl+equal change_font_size all +1
map ctrl+minus change_font_size all -1

# ~~ turned off terminal navigation to avoid keybind override text selection ~~
map ctrl+shift+up no_op
map ctrl+shift+down no_op
map ctrl+shift+left no_op
map ctrl+shift+right no_op

# ~~ kitty tab navigation alternative ~~
map ctrl+shift+] next_tab
map ctrl+shift+[ previous_tab
