
#    ░██       ░██   ░██       ░██
#    ░██             ░██       ░██
#    ░██    ░██░██░████████ ░████████ ░██    ░██
#    ░██   ░██ ░██   ░██       ░██    ░██    ░██
#    ░███████  ░██   ░██       ░██    ░██    ░██
#    ░██   ░██ ░██   ░██       ░██    ░██   ░███
#    ░██    ░██░██    ░████     ░████  ░█████░██
#                                            ░██
#                                      ░███████
#
#	 github: @plgbrlism
#	 tiktok: @fuzzbuzz.tech

include colors/colors.conf
include fonts/fonts.conf
include transparency.conf
include window.conf
include keybind.conf
