
#    ░██       ░██   ░██       ░██               
#    ░██             ░██       ░██               
#    ░██    ░██░██░████████ ░████████ ░██    ░██ 
#    ░██   ░██ ░██   ░██       ░██    ░██    ░██ 
#    ░███████  ░██   ░██       ░██    ░██    ░██ 
#    ░██   ░██ ░██   ░██       ░██    ░██   ░███ 
#    ░██    ░██░██    ░████     ░████  ░█████░██ 
#                                            ░██ 
#                                      ░███████  
#                                                
#	 github: @plgbrlism                                              
#	 tiktok: @sivops.tech

include colors/colors.conf
include fonts/fonts.conf
include transparency.conf
include window.conf
include keybind.conf
