#!/bin/bash

if [ -f /tmp/_rb_shared ]; then source /tmp/_rb_shared; else exit 1; fi

notify() {
    notify-send -u low -t 2000 "Bluetooth Profiles" "$1"
}

if [ "$IS_ON" != true ]; then
    notify "Error: Controller is off!"
    exit 1
fi

# load cached devices generated by our master thread fork
mapfile -t PAIRED < /tmp/_rb_devices_list
# Map active links to check status dynamically
mapfile -t CONNECTED < /tmp/_rb_connected_list

ICON_BACK="󱞳 "

options=()
options+=("$ICON_BACK Back")

for dev in "${PAIRED[@]}"; do
    if [[ -n "$dev" ]]; then
        mac=$(echo "$dev" | awk '{print $2}')
        name=$(echo "$dev" | cut -d' ' -f3-)

        # check if mac exists inside cache
        if grep -q "$mac" /tmp/_rb_connected_list; then
            options+=("$mac - $name 󰄬 (Connected)")
        else
            options+=("$mac - $name")
        fi
    fi
done

chosen_idx=$(printf "%s\n" "${options[@]}" | wofi --dmenu \
    --style "$style" \
    --width 450 \
    --define "dmenu-print_line_num=true" \
    --insensitive)

if [[ -z "$chosen_idx" ]] || [ "$chosen_idx" -eq 0 ]; then
    exec "$SCRIPT_DIR/rofi-bluetooth.sh"
fi

SELECTED="${options[$chosen_idx]}"
MAC=$(echo "$SELECTED" | awk '{print $1}')
NAME=$(echo "$SELECTED" | cut -d'-' -f2- | sed 's/ 󰄬 (Connected)//')

if [ -n "$MAC" ]; then
    if grep -q "$MAC" /tmp/_rb_connected_list; then
        notify "Severing link to$NAME..."
        bluetoothctl disconnect "$MAC" && notify "Disconnected cleanly."
    else
        notify "Routing link to$NAME..."
        bluetoothctl connect "$MAC" && notify "Link Established!" || notify "Link aborted."
    fi
    sleep 0.5; exec "$SCRIPT_DIR/rofi-bluetooth.sh"
fi
