# btop theme
# Generated with rizzoo

theme[main_bg]=""
theme[main_fg]="#eedfe0"
theme[title]="#ce939d"
theme[hi_fg]="#bb9b9f"
theme[selected_bg]="#ce939d"
theme[selected_fg]="#2e0b14"
theme[inactive_fg]="#d5c2c4"
theme[proc_misc]="#c09d78"
theme[cpu_box]="#9d8d8f"
theme[mem_box]="#9d8d8f"
theme[net_box]="#9d8d8f"
theme[proc_box]="#9d8d8f"
theme[div_line]="#504445"

theme[temp_start]="#bb9b9f"
theme[temp_mid]="#ce939d"
theme[temp_end]="#ff7b6e"

theme[cpu_start]="#bb9b9f"
theme[cpu_mid]="#ce939d"
theme[cpu_end]="#ff7b6e"

theme[free_start]="#bb9b9f"
theme[free_mid]=""
theme[free_end]="#fedade"

theme[cached_start]="#c09d78"
theme[cached_mid]=""
theme[cached_end]="#ffddbb"

theme[available_start]="#ce939d"
theme[available_mid]=""
theme[available_end]="#ffd9de"

theme[used_start]="#ff7b6e"
theme[used_mid]=""
theme[used_end]="#ffdad6"

theme[download_start]="#bb9b9f"
theme[download_mid]="#ce939d"
theme[download_end]="#c09d78"

theme[upload_start]="#bb9b9f"
theme[upload_mid]="#ce939d"
theme[upload_end]="#c09d78"
