# btop theme
# Generated with rizzoo

theme[main_bg]=""
theme[main_fg]="#eee0d9"
theme[title]="#cf9677"
theme[hi_fg]="#bc9c8c"
theme[selected_bg]="#cf9677"
theme[selected_fg]="#2d0f00"
theme[inactive_fg]="#d5c3ba"
theme[proc_misc]="#a9a479"
theme[cpu_box]="#9e8d86"
theme[mem_box]="#9e8d86"
theme[net_box]="#9e8d86"
theme[proc_box]="#9e8d86"
theme[div_line]="#51443e"

theme[temp_start]="#bc9c8c"
theme[temp_mid]="#cf9677"
theme[temp_end]="#ff7b6e"

theme[cpu_start]="#bc9c8c"
theme[cpu_mid]="#cf9677"
theme[cpu_end]="#ff7b6e"

theme[free_start]="#bc9c8c"
theme[free_mid]=""
theme[free_end]="#ffdbca"

theme[cached_start]="#a9a479"
theme[cached_mid]=""
theme[cached_end]="#e9e4b4"

theme[available_start]="#cf9677"
theme[available_mid]=""
theme[available_end]="#ffdbca"

theme[used_start]="#ff7b6e"
theme[used_mid]=""
theme[used_end]="#ffdad6"

theme[download_start]="#bc9c8c"
theme[download_mid]="#cf9677"
theme[download_end]="#a9a479"

theme[upload_start]="#bc9c8c"
theme[upload_mid]="#cf9677"
theme[upload_end]="#a9a479"
