# btop theme
# Generated with rizzoo

theme[main_bg]=""
theme[main_fg]="#e1e2e7"
theme[title]="#86a6c4"
theme[hi_fg]="#97a4b2"
theme[selected_bg]="#86a6c4"
theme[selected_fg]="#00192b"
theme[inactive_fg]="#c3c7cd"
theme[proc_misc]="#ab9dbc"
theme[cpu_box]="#8d9197"
theme[mem_box]="#8d9197"
theme[net_box]="#8d9197"
theme[proc_box]="#8d9197"
theme[div_line]="#42474c"

theme[temp_start]="#97a4b2"
theme[temp_mid]="#86a6c4"
theme[temp_end]="#ff7b6e"

theme[cpu_start]="#97a4b2"
theme[cpu_mid]="#86a6c4"
theme[cpu_end]="#ff7b6e"

theme[free_start]="#97a4b2"
theme[free_mid]=""
theme[free_end]="#d6e4f3"

theme[cached_start]="#ab9dbc"
theme[cached_mid]=""
theme[cached_end]="#ecdcfe"

theme[available_start]="#86a6c4"
theme[available_mid]=""
theme[available_end]="#cce5ff"

theme[used_start]="#ff7b6e"
theme[used_mid]=""
theme[used_end]="#ffdad6"

theme[download_start]="#97a4b2"
theme[download_mid]="#86a6c4"
theme[download_end]="#ab9dbc"

theme[upload_start]="#97a4b2"
theme[upload_mid]="#86a6c4"
theme[upload_end]="#ab9dbc"
