#[module/backlight]
#type = internal/backlight
#format = <label>
#label = "%{A1:~/.config/rofi/scripts/brightness/rofi-brightness.sh:}󰃠  %percentage%%%{A}"
#label-foreground = ${colors.primary}
#enable-scroll = true

[module/backlight]
type = internal/backlight
format = <label>
label = "%{A1:~/.config/rofi/scripts/brightness/rofi-brightness.sh:}%{T2}󰃠%{T-} %percentage%%%{A}"
label-foreground = ${colors.primary}
enable-scroll = true
