# ~~ rules ~~

rules = (
  # Tooltips
  {
    match = "window_type = 'tooltip'";
    fade = false;
    shadow = false;
    opacity = 0.9;
    full-shadow = false;
    blur-background = false;
    frame = false;
  },

  # Browser pop-up menu
  {
    match = "class_g = 'firefox-esr' && window_type = 'popup_menu'";
    fade = false;
    shadow = false;
    opacity = 0.9;
    full-shadow = false;
    blur-background = false;
    frame = false;
  },

  {
    match = "class_g = 'brave-browser'";
    fade = true;
    shadow = true;
    opacity = 0.40;
    full-shadow = false;
    blur-background = false;
    frame = false;
  },

  # Browser context menus
  {
    match = "window_type = 'utility' || window_type = 'dialog'";
    fade = false;
    shadow = false;
    blur-background = false;
    frame = false;
  },

  # Panels, docks, desktop
  {
    match = "window_type = 'dock' || window_type = 'desktop'";
    blur-background = false;
    corner-radius = 0;
    shadow = false;
    fade = false;
  },

  # Notifications
  {
    match = "name = 'Notification' || class_g = 'Dunst' || class_g = 'Conky' || class_g ?= 'Notify-osd' || class_g = 'Cairo-clock'";
    shadow = false;
    opacity = 0.95;
    fade = true;
  },

  # Bar
  {
    match = "class_g = 'Polybar'";
    shadow = false;
    blur-background = false;
    fade = false;
  },

  # App Launcher [Rofi]
  {
    match = "class_g = 'Rofi'";
    shadow = false;
    blur-background = true;
    opacity = 1.0;
  },

  # File Manager
  {
    match = "class_g = 'Nemo'";
    shadow = true;
    blur-background = true;
    opacity = 0.90;
  },

  # IDE
  {
    match = "class_g =  'Antigravity'";
    shadow = false;
    opacity = 0.96;
  },

@include "conf/animations.conf"

  # Default unfocused opacity for all
  {
    match = "!focused && class_g != 'Nemo'";
    opacity = 1.0
    dim = 0.2;
  }
)
