# ~~ Battery Capacity ~~
label {
    text = cmd[update:10000] echo "󰁹   $(cat /sys/class/power_supply/BAT0/capacity)%"
    color = rgba(216, 222, 233, 0.73)
    font_size = 13
    font_family = $font-0
    position = -20, 15
    halign = right
    valign = bottom
}
