# ~~ Clock & Date ~~
# Time
label {
    text = $TIME12
    color = rgba(216, 222, 233, 0.85)
    font_size = 65
    font_family = $font-0
    position = 0, 200
    halign = center
    valign = center
}

# Date
label {
    text = cmd[update:28800000] date +'%A, %d %B'
    color = rgba(216, 222, 233, 0.5)
    font_size = 13
    font_family = $font-0
    position = 0, 135
    halign = center
    valign = center
}

# ~~ Date ~~
label {
    text = <span>   Locked</span>
    color = rgba(216, 222, 233, 0.73)
    font_size = 13
    font_family = $font-0
    position = 0, 15
    halign = center
    valign = bottom
}
