#   
#               ░██                                ░██   ░██       ░██               
#               ░██                                      ░██       ░██               
#     ░██████   ░██  ░██████    ░███████  ░██░████ ░██░████████ ░████████ ░██    ░██ 
#          ░██  ░██       ░██  ░██    ░██ ░███     ░██   ░██       ░██    ░██    ░██ 
#     ░███████  ░██  ░███████  ░██        ░██      ░██   ░██       ░██    ░██    ░██ 
#    ░██   ░██  ░██ ░██   ░██  ░██    ░██ ░██      ░██   ░██       ░██    ░██   ░███ 
#     ░█████░██ ░██  ░█████░██  ░███████  ░██      ░██    ░████     ░████  ░█████░██ 
#                                                                                ░██ 
#                                                                          ░███████  
#	 github: @plgbrlism
#	 tiktok: @fuzzbuzz.tech                                                                                 

[general]
import = [
	"~/.config/alacritty/colors/colors.toml",
	"~/.config/alacritty/fonts/fonts.toml",
	"~/.config/alacritty/window.toml",
	"~/.config/alacritty/keybind.toml"
]
