# ~~ applications / scripts ~~

set $bar                 ~/.config/i3/helper/polybar/on-launch.sh
set $compositor          ~/.local/bin/dispatch compositor
set $terminal            ~/.local/bin/dispatch terminal
set $browser             ~/.local/bin/dispatch browser
set $file-manager        ~/.local/bin/dispatch file-manager
set $terminal-fm         ~/.local/bin/dispatch terminal-fm
set $app_launcher        ~/.config/rofi/scripts/app_launcher/app_launcher.sh
set $session_manager     ~/.config/rofi/scripts/session_manager/session_manager.sh
set $powermenu           ~/.config/rofi/scripts/powermenu/powermenu.sh
