# ~~ applications / scripts ~~

set $bar                 ~/.config/i3/helper/polybar/on-launch.sh
set $compositor          picom
set $terminal            kitty
set $browser             firefox
set $file-manager        nautilus
set $terminal-fm         kitty -e yazi
set $app_launcher        ~/.config/rofi/scripts/app_launcher/app_launcher.sh
set $session_manager     ~/.config/rofi/scripts/session_manager/session_manager.sh
set $powermenu           ~/.config/rofi/scripts/powermenu/powermenu.sh
