# ~~ autostart ~~

exec_always --no-startup-id $bar
exec_always --no-startup-id $compositor
exec --no-startup-id dunst
# exec --no-startup-id /usr/libexec/polkit-mate-authentication-agent-1

# ~~ wallpaper reload ~~
exec --no-startup-id ~/.config/rofi/scripts/wallpaper/cache-wallpaper.sh --restore
