# ~~ keybinds ~~

# Mod keys
set $windows-key Mod4
set $alt-key Mod1
floating_modifier $windows-key
tiling_drag swap_modifier Shift


# Core actions
bindsym $windows-key+Return exec --no-startup-id $terminal
bindsym $windows-key+e exec --no-startup-id $file-manager
bindsym $windows-key+y exec --no-startup-id $terminal-fm
bindsym $windows-key+r exec --no-startup-id $app_launcher
bindsym $windows-key+Escape exec --no-startup-id $session_manager
bindsym $windows-key+p exec --no-startup-id $powermenu

bindsym $windows-key+c kill
bindsym $windows-key+f fullscreen toggle
bindsym $windows-key+v floating toggle
bindsym $windows-key+m exec "i3-msg exit"
bindsym $windows-key+Shift+r reload
bindsym $windows-key+Shift+e restart



# Workspaces
bindsym $windows-key+1 workspace 1
bindsym $windows-key+2 workspace 2
bindsym $windows-key+3 workspace 3
bindsym $windows-key+4 workspace 4
bindsym $windows-key+5 workspace 5
bindsym $windows-key+6 workspace 6
bindsym $windows-key+7 workspace 7
bindsym $windows-key+8 workspace 8
bindsym $windows-key+9 workspace 9
bindsym $windows-key+0 workspace 10

bindsym $alt-key+Tab workspace next_on_output
bindsym $alt-key+Shift+Tab workspace prev_on_output

bindsym $windows-key+Shift+1 move container to workspace 1
bindsym $windows-key+Shift+2 move container to workspace 2
bindsym $windows-key+Shift+3 move container to workspace 3
bindsym $windows-key+Shift+4 move container to workspace 4
bindsym $windows-key+Shift+5 move container to workspace 5
bindsym $windows-key+Shift+6 move container to workspace 6
bindsym $windows-key+Shift+7 move container to workspace 7
bindsym $windows-key+Shift+8 move container to workspace 8
bindsym $windows-key+Shift+9 move container to workspace 9
bindsym $windows-key+Shift+0 move container to workspace 10

# Focus Mode (WASD)
bindsym $windows-key+h focus left
bindsym $windows-key+l focus right
bindsym $windows-key+k focus up
bindsym $windows-key+j focus down

# Swap Windows (Shift+WASD)
bindsym $windows-key+Shift+h exec --no-startup-id ~/.local/bin/i3-qol swap left
bindsym $windows-key+Shift+l exec --no-startup-id ~/.local/bin/i3-qol swap right
bindsym $windows-key+Shift+k exec --no-startup-id ~/.local/bin/i3-qol swap up
bindsym $windows-key+Shift+j exec --no-startup-id ~/.local/bin/i3-qol swap down

# Resize Windows (Ctrl+WASD)
bindsym $windows-key+Ctrl+k resize grow height 50 px
bindsym $windows-key+Ctrl+j resize shrink height 50 px
bindsym $windows-key+Ctrl+h resize grow width 50 px
bindsym $windows-key+Ctrl+l resize shrink width 50 px

# Tiling Drag Modifier (mod+Shift)
bindsym $windows-key+Shift+left move left
bindsym $windows-key+Shift+down move down
bindsym $windows-key+Shift+up  move up
bindsym $windows-key+Shift+right move right
