# ╭──────────────────────────────╮
# │       Keyboard Binding       │
# ╰──────────────────────────────╯

# Mod Key
set $mod Mod4
floating_modifier $mod
tiling_drag swap_modifier Shift

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

bindsym --whole-window $mod+button4  exec i3-qol resize grow -p 50
bindsym --whole-window $mod+button5  exec i3-qol resize shrink -p 50

# Core Actions
bindsym $mod+q exec $terminal
bindsym $mod+e exec $file_manager
bindsym $mod+y exec $terminal_FM
bindsym $mod+c kill
bindsym $mod+f fullscreen toggle
bindsym $mod+v floating toggle
bindsym $mod+r exec $app_launcher
bindsym $mod+Escape exec $session_manager
bindsym $mod+p exec $powermenu
bindsym $mod+m exec "i3-msg exit"
bindsym $mod+Shift+r reload
bindsym $mod+Shift+e restart

# Workspaces
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

bindsym Mod1+Tab workspace next_on_output
bindsym Mod1+Shift+Tab workspace prev_on_output

bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# Focus Mode (WASD)
bindsym $mod+a exec i3-msg focus left
bindsym $mod+d exec i3-msg focus right
bindsym $mod+w exec i3-msg focus up
bindsym $mod+s exec i3-msg focus down

# Swap Windows (Shift+WASD)
bindsym $mod+Shift+a exec --no-startup-id ~/.local/bin/i3-qol swap left
bindsym $mod+Shift+d exec --no-startup-id ~/.local/bin/i3-qol swap right
bindsym $mod+Shift+w exec --no-startup-id ~/.local/bin/i3-qol swap up
bindsym $mod+Shift+s exec --no-startup-id ~/.local/bin/i3-qol swap down

# Resize Windows (Ctrl+WASD)
bindsym $mod+Ctrl+w resize grow height 100 px
bindsym $mod+Ctrl+s resize shrink height 100 px
bindsym $mod+Ctrl+a resize grow width 100 px
bindsym $mod+Ctrl+d resize shrink width 100 px
