# ╭──────────────────────────────╮
# │      Colors & Resources      │
# ╰──────────────────────────────╯

#include ~/dotfiles/i3/.config/i3/colors-i3.conf
#exec_always --no-startup-id xrdb -merge ~/.cache/rwal/colors.Xresources

# ╭──────────────────────────────╮
# │Disable Screen Blanking & DPMS│
# ╰──────────────────────────────╯

exec --no-startup-id xset s off
exec --no-startup-id xset -dpms
exec --no-startup-id xset s noblank
