# ~~ display power management signals ~~
# this is a hardware specific setup to disable sleep/suspend states
# (do not copy unless ur hardware can properly do sleep/suspend states)

exec --no-startup-id xset s off
exec --no-startup-id xset -dpms
exec --no-startup-id xset s noblank
