# ~~ system level configurations (do not copy unless needed)

# exec --no-startup-id /usr/libexec/xdg-desktop-portal-gtk
# exec --no-startup-id /usr/libexec/xdg-desktop-portal

# ~~ laptop power optimization ~~
exec --no-startup-id sudo /usr/sbin/powertop --auto-tune 
