;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;
;==========================================================

; ~~ DEFAULT [FLAT] ~~
; --- Base ---
include-file = colors/colors.ini

; --- Bar geometry ---
include-file = bar/flat.ini

; --- Fonts ---
include-file = fonts/fonts.ini

;--- Sequence ---
[bar/main]
modules-left   = powermenu xworkspaces xwindow 
modules-center = 
modules-right  = systray sep pulseaudio backlight sep wlan sep battery sep cpu

; --- Modules ---
include-file = modules/icons/sep.ini
include-file = modules/icons/systray.ini
include-file = modules/icons/network-base.ini
include-file = modules/icons/xworkspaces-icons.ini
include-file = modules/icons/xwindow-icons.ini
include-file = modules/icons/memory.ini
include-file = modules/icons/cpu.ini
include-file = modules/icons/pulseaudio-icons.ini
include-file = modules/icons/backlight.ini
include-file = modules/icons/wlan-icons.ini
include-file = modules/icons/battery-icons.ini
include-file = modules/icons/powermenu.ini




;; ~~ FLOATING ~~
;; --- Base ---
;include-file = colors/colors.ini
;
;; --- Bar geometry ---
;include-file = bar/floating.ini
;
;; --- Fonts ---
;include-file = fonts/fonts.ini
;
;;--- Sequence ---
;[bar/main]
;modules-left   = powermenu xworkspaces xwindow 
;modules-center = 
;modules-right  = systray sep pulseaudio backlight sep wlan sep battery sep cpu
;
;; --- Modules ---
;include-file = modules/icons/sep.ini
;include-file = modules/icons/systray.ini
;include-file = modules/icons/network-base.ini
;include-file = modules/icons/xworkspaces-icons.ini
;include-file = modules/icons/xwindow-icons.ini
;include-file = modules/icons/memory.ini
;include-file = modules/icons/cpu.ini
;include-file = modules/icons/pulseaudio-icons.ini
;include-file = modules/icons/backlight.ini
;include-file = modules/icons/wlan-icons.ini
;include-file = modules/icons/battery-icons.ini
;include-file = modules/icons/powermenu.ini



;; ~~ MINIMAL ~~
;; --- Base ---
;include-file = colors/colors.ini
;
;; --- Bar geometry == minimal ---
;include-file = bar/minimal.ini
;
;; --- Fonts ---
;include-file = fonts/fonts.ini
;
;; --- Sequence ---
;[bar/main]
;modules-left   = xworkspaces 
;modules-center = powermenu 
;modules-right  = systray battery
;
;; --- Modules ---
;include-file = modules/icons/systray.ini
;include-file = modules/icons/xworkspaces-icons.ini
;include-file = modules/icons/battery-icons.ini
;include-file = modules/icons/powermenu.ini

;; ~~ SIMPLE [no icons/ glyphs] ~~
;; --- Base ---
;include-file = colors/colors.ini
;
;; --- Bar geometry ---
;include-file = bar/flat.ini
;
;; --- Fonts ---
;include-file = fonts/fonts.ini
;
;;--- Sequence ---
;[bar/main]
;modules-left   = powermenu xworkspaces xwindow 
;modules-center = 
;modules-right  = systray sep pulseaudio backlight sep wlan sep battery sep cpu
;
;; --- Modules ---
;include-file = modules/no-icons/sep.ini
;include-file = modules/no-icons/systray.ini
;include-file = modules/no-icons/network-base.ini
;include-file = modules/no-icons/xworkspaces-icons.ini
;include-file = modules/no-icons/xwindow-icons.ini
;include-file = modules/no-icons/memory.ini
;include-file = modules/no-icons/cpu.ini
;include-file = modules/no-icons/pulseaudio-icons.ini
;include-file = modules/no-icons/backlight.ini
;include-file = modules/no-icons/wlan-icons.ini
;include-file = modules/no-icons/battery-icons.ini
;include-file = modules/no-icons/powermenu.ini
