# ~~ applications ~~

set $terminal            ~/.local/bin/dispatch terminal
set $browser             ~/.local/bin/dispatch browser
set $file_manager        ~/.local/bin/dispatch file-manager
set $terminal_FM         ~/.local/bin/dispatch terminal-fm
