# ───────────────────────────────
# Applications
# ───────────────────────────────

set $bar                 ~/.config/sway/helper/waybar/on-launch.sh
set $terminal            kitty
set $browser             firefox
set $file_manager        nemo
set $terminal_FM         kitty -e yazi
set $app_launcher        ~/.config/rofi/scripts/app_launcher/app_launcher.sh
set $session_manager     ~/.config/rofi/scripts/session_manager/session_manager.sh
set $powermenu            ~/.config/rofi/scripts/powermenu/powermenu.sh
