# ~~ autostart ~~

exec_always pkill -x swaybg
exec_always $bar
exec dunst
exec ~/.config/rofi/scripts/wallpaper/cache-wallpaper.sh --restore

# exec /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
