# ~~ system level configurations (do not copy unless needed)

# 1. Force systemd to see that $WAYLAND_DISPLAY now exists
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

# 2. Tell systemd to fire up the GTK portal service now that the condition is met
exec systemctl --user start xdg-desktop-portal-gtk

# ~~ laptop power optimization ~~
exec --no-startup-id sudo /usr/sbin/powertop --auto-tune 
