# ───────────────────────────────
# Touchpad
# ───────────────────────────────

input "type:touchpad" {
    tap enabled
    tap_button_map lrm
    dwt enabled
    drag_lock disabled
    scroll_factor 0.9
}
