# qtile colors — Calamus Umber
# generated by calamus

colors = {
    # client / window
    "focused": "#a8a56c",
    "focused_bg": "#202019",
    "focused_inactive": "#14140d",
    "unfocused": "#14140d",
    "urgent": "#ff7b6e",
    "urgent_fg": "#390001",
    "placeholder": "#0f0e08",
    "background": "#14140d",

    # palette
    "primary": "#a8a56c",
    "on_primary": "#191800",
    "primary_fixed_dim": "#ccc98d",
    "on_primary_fixed": "#1e1d00",
    "secondary": "#a7a487",
    "on_secondary": "#191805",
    "tertiary": "#89aa9a",
    "on_tertiary": "#001c12",
    "error": "#ff7b6e",
    "on_error": "#390001",
    "surface": "#14140d",
    "on_surface": "#e6e2d7",
    "surface_container": "#202019",
    "surface_container_low": "#1c1c15",
    "surface_container_high": "#2b2a23",
    "surface_bright": "#3a3932",
    "on_surface_variant": "#cac7b8",
    "outline": "#939183",
}
