# qtile colors — Calamus Papyrus
# generated by calamus

colors = {
    # client / window
    "focused": "#636122",
    "focused_bg": "#f2eee0",
    "focused_inactive": "#fdf9ec",
    "unfocused": "#fdf9ec",
    "urgent": "#bb1b1b",
    "urgent_fg": "#ffffff",
    "placeholder": "#ffffff",
    "background": "#fdf9ec",

    # palette
    "primary": "#636122",
    "on_primary": "#ffffff",
    "primary_fixed_dim": "#cdca7f",
    "on_primary_fixed": "#1e1d00",
    "secondary": "#626043",
    "on_secondary": "#ffffff",
    "tertiary": "#3f6756",
    "on_tertiary": "#ffffff",
    "error": "#bb1b1b",
    "on_error": "#ffffff",
    "surface": "#fdf9ec",
    "on_surface": "#1c1c14",
    "surface_container": "#f2eee0",
    "surface_container_low": "#f8f4e6",
    "surface_container_high": "#ece8db",
    "surface_bright": "#fdf9ec",
    "on_surface_variant": "#48473a",
    "outline": "#797769",
}
