# qtile colors
# generated by rizzoo

colors = {
    # client / window
    "focused": "#8ca5c7",
    "focused_bg": "#1e2023",
    "focused_inactive": "#111317",
    "unfocused": "#111317",
    "urgent": "#ff7b6e",
    "urgent_fg": "#390001",
    "placeholder": "#0c0e12",
    "background": "#111317",

    # palette
    "primary": "#8ca5c7",
    "on_primary": "#001831",
    "primary_fixed_dim": "#b0c8ec",
    "on_primary_fixed": "#001c37",
    "secondary": "#9aa3b4",
    "on_secondary": "#0e1824",
    "tertiary": "#b09cb9",
    "on_tertiary": "#201228",
    "error": "#ff7b6e",
    "on_error": "#390001",
    "surface": "#111317",
    "on_surface": "#e2e2e7",
    "surface_container": "#1e2023",
    "surface_container_low": "#191c1f",
    "surface_container_high": "#282a2e",
    "surface_bright": "#37393d",
    "on_surface_variant": "#c4c6ce",
    "outline": "#8e9198",
}
