# qtile colors
# generated by rizzoo

colors = {
    # client / window
    "focused": "#97a979",
    "focused_bg": "#1e201b",
    "focused_inactive": "#12140f",
    "unfocused": "#12140f",
    "urgent": "#ff7b6e",
    "urgent_fg": "#390001",
    "placeholder": "#0d0f0a",
    "background": "#12140f",

    # palette
    "primary": "#97a979",
    "on_primary": "#0e1b00",
    "primary_fixed_dim": "#bacd9a",
    "on_primary_fixed": "#121f01",
    "secondary": "#9ea68d",
    "on_secondary": "#131a09",
    "tertiary": "#86aaa6",
    "on_tertiary": "#001c19",
    "error": "#ff7b6e",
    "on_error": "#390001",
    "surface": "#12140f",
    "on_surface": "#e3e3da",
    "surface_container": "#1e201b",
    "surface_container_low": "#1a1c17",
    "surface_container_high": "#292b25",
    "surface_bright": "#383a33",
    "on_surface_variant": "#c6c8bb",
    "outline": "#8f9286",
}
