# qtile colors
# generated by rizzoo

colors = {
    # client / window
    "focused": "#a79dc8",
    "focused_bg": "#201f23",
    "focused_inactive": "#141317",
    "unfocused": "#141317",
    "urgent": "#ff7b6e",
    "urgent_fg": "#390001",
    "placeholder": "#0f0e12",
    "background": "#141317",

    # palette
    "primary": "#a79dc8",
    "on_primary": "#191234",
    "primary_fixed_dim": "#cbc0ed",
    "on_primary_fixed": "#1d1638",
    "secondary": "#a6a0b4",
    "on_secondary": "#191525",
    "tertiary": "#c297a6",
    "on_tertiary": "#290f1a",
    "error": "#ff7b6e",
    "on_error": "#390001",
    "surface": "#141317",
    "on_surface": "#e6e1e7",
    "surface_container": "#201f23",
    "surface_container_low": "#1c1b1f",
    "surface_container_high": "#2b292e",
    "surface_bright": "#3a383d",
    "on_surface_variant": "#cac5ce",
    "outline": "#938f98",
}
