# Dynamic Colorscheme

theme[available_end]="{{ error.hex }}"
theme[available_mid]="{{ warning.hex }}"
theme[available_start]="{{ success.hex }}"

theme[cached_end]="{{ error.hex }}"
theme[cached_mid]="{{ warning.hex }}"
theme[cached_start]="{{ success.hex }}"

theme[cpu_box]="{{ primary.hex }}"
theme[cpu_end]="{{ error.hex }}"
theme[cpu_mid]="{{ warning.hex }}"
theme[cpu_start]="{{ success.hex }}"

theme[div_line]="{{ primary.hex }}"

theme[download_end]="{{ error.hex }}"
theme[download_mid]="{{ warning.hex }}"
theme[download_start]="{{ success.hex }}"

theme[free_end]="{{ error.hex }}"
theme[free_mid]="{{ warning.hex }}"
theme[free_start]="{{ success.hex }}"

theme[hi_fg]="{{ primary.hex }}"
theme[inactive_fg]="{{ overlay.hex }}"

theme[main_bg]="{{ background.hex }}"
theme[main_fg]="{{ foreground.hex }}"

theme[mem_box]="{{ primary.hex }}"
theme[net_box]="{{ primary.hex }}"
theme[proc_box]="{{ primary.hex }}"
theme[proc_misc]="{{ secondary.hex }}"

theme[selected_bg]="{{ surface.hex }}"
theme[selected_fg]="{{ foreground.hex }}"

theme[temp_end]="{{ error.hex }}"
theme[temp_mid]="{{ warning.hex }}"
theme[temp_start]="{{ success.hex }}"

theme[title]="{{ foreground.hex }}"

theme[upload_end]="{{ error.hex }}"
theme[upload_mid]="{{ warning.hex }}"
theme[upload_start]="{{ success.hex }}"

theme[used_end]="{{ error.hex }}"
theme[used_mid]="{{ warning.hex }}"
theme[used_start]="{{ success.hex }}"
