# colors_tty.sh — generated by rwal
# Source this file or run it to apply colors to the Linux TTY.
# Only has effect on a real TTY (not a terminal emulator).

if [ "$TERM" = "linux" ]; then
    printf '\e]P0{{ color0.hex }}'   # black
    printf '\e]P1{{ color1.hex }}'   # red
    printf '\e]P2{{ color2.hex }}'   # green
    printf '\e]P3{{ color3.hex }}'   # yellow
    printf '\e]P4{{ color4.hex }}'   # blue
    printf '\e]P5{{ color5.hex }}'   # magenta
    printf '\e]P6{{ color6.hex }}'   # cyan
    printf '\e]P7{{ color7.hex }}'   # white
    printf '\e]P8{{ color8.hex }}'   # bright black
    printf '\e]P9{{ color9.hex }}'   # bright red
    printf '\e]PA{{ color10.hex }}'  # bright green
    printf '\e]PB{{ color11.hex }}'  # bright yellow
    printf '\e]PC{{ color12.hex }}'  # bright blue
    printf '\e]PD{{ color13.hex }}'  # bright magenta
    printf '\e]PE{{ color14.hex }}'  # bright cyan
    printf '\e]PF{{ color15.hex }}'  # bright white
    clear                    # flush color artifacts
fi