
;                       ░██            ░██                            
;                       ░██            ░██                            
; ░████████   ░███████  ░██ ░██    ░██ ░████████   ░██████   ░██░████ 
; ░██    ░██ ░██    ░██ ░██ ░██    ░██ ░██    ░██       ░██  ░███     
; ░██    ░██ ░██    ░██ ░██ ░██    ░██ ░██    ░██  ░███████  ░██      
; ░███   ░██ ░██    ░██ ░██ ░██   ░███ ░███   ░██ ░██   ░██  ░██      
; ░██░█████   ░███████  ░██  ░█████░██ ░██░█████   ░█████░██ ░██      
; ░██                              ░██                                
; ░██                        ░███████                                 

; ╭────────────────────────╮
; │ github: @plgbrlism     │
; │ tiktok: @fuzzbuzz.tech │
; ╰────────────────────────╯

; ~~ FLOATING ~~
; --- Base ---
include-file = colors/colors.ini

; --- Bar geometry ---
include-file = bar/floating.ini

; --- Fonts ---
include-file = fonts/fonts.ini

;--- Sequence ---
[bar/main]
modules-left   = powermenu xworkspaces xwindow 
modules-center = 
modules-right  = systray sep pulseaudio backlight sep wlan sep battery sep cpu

; --- Modules ---
include-file = modules/icons/sep.ini
include-file = modules/icons/systray.ini
include-file = modules/icons/network-base.ini
include-file = modules/icons/xworkspaces-icons.ini
include-file = modules/icons/xwindow-icons.ini
include-file = modules/icons/memory.ini
include-file = modules/icons/cpu.ini
include-file = modules/icons/pulseaudio-icons.ini
include-file = modules/icons/backlight.ini
include-file = modules/icons/wlan-icons.ini
include-file = modules/icons/battery-icons.ini
include-file = modules/icons/powermenu.ini
