
;                       ░██            ░██                            
;                       ░██            ░██                            
; ░████████   ░███████  ░██ ░██    ░██ ░████████   ░██████   ░██░████ 
; ░██    ░██ ░██    ░██ ░██ ░██    ░██ ░██    ░██       ░██  ░███     
; ░██    ░██ ░██    ░██ ░██ ░██    ░██ ░██    ░██  ░███████  ░██      
; ░███   ░██ ░██    ░██ ░██ ░██   ░███ ░███   ░██ ░██   ░██  ░██      
; ░██░█████   ░███████  ░██  ░█████░██ ░██░█████   ░█████░██ ░██      
; ░██                              ░██                                
; ░██                        ░███████                                 

; ╭────────────────────────╮
; │ github: @plgbrlism     │
; │ tiktok: @fuzzbuzz.tech │
; ╰────────────────────────╯

; ~~ MINIMAL ~~
; --- Base ---
include-file = colors/colors.ini

; --- Bar geometry == minimal ---
include-file = bar/minimal.ini

; --- Fonts ---
include-file = fonts/fonts.ini

; --- Sequence ---
[bar/main]
modules-left   = 
modules-center = xworkspaces xwindow systray
modules-right  = 

; --- Modules ---
include-file = modules/icons/systray.ini
include-file = modules/icons/xworkspaces-icons.ini
include-file = modules/icons/xwindow-icons.ini
include-file = modules/icons/powermenu.ini
